### ISSUE TITLE
Decrypt in-place

### ISSUE THREAD

**Issue by gallagherman** [meld-cp/obsidian-encrypt#1]
This is a very cool plugin! Would it be possible to add an option to "decrypt in-place," which would replace the encrypted text with the decoded text without having to copy/paste it from the dialog box?

**Comment by meld-cp** [comment]
Thanks @gallagherman.   Absolutely, I'll add it to the next version.

**Comment by meld-cp** [comment]
I just released 1.1.0, please test decrypt in-place and let me know how it works for you.  Thanks for the feedback.

**Comment by gallagherman** [comment]
Works well! Great! The only thing I would suggest is to have an options pane in the plugin options panel to enable it and skip presenting the dialog box altogether. This way a user could seamlessly switch back and forth from encrypted and decrypted with the same command. I do see value in the dialog box, however, so it would be worth having the ability to choose.

**Comment by meld-cp** [comment]
Yeah, I thought about always decrypting in-place without the dialog, but the issue with that is you then need to remember to re-encrypt the secret before exiting Obsidian.   On the other hand, I also see the use case where you want to decrypt a bunch of things quickly without having to copy/paste off a dialog.  So, I think the best way to deal with both cases is to add another command in the palette which will always decrypt in-place.  This way the user can bind each version to a keyboard shortcut and, depending on their workflow, choose whichever they like  (decrypt in-dialog or decrypt in-place).
