### ISSUE TITLE
Sudden decryption failed today

### ISSUE THREAD

**Issue by hanju-java** [meld-cp/obsidian-encrypt#101]
I remember the password and opened the encrypted file 30 minute ago

I never change the password，and used normally for two months

today , after restart obsidian，can't decryption the file  anymore。

I have some important password in the file, please help me

**Comment by meld-cp** [comment]
Hi @hanju-java, I'm sorry you've run into issues.

There's a big warning in the readme page saying that there won't be much I can do if the encryption fails for any reason.

Which kind of encryption were you using, full note or the comment/in-place encryption?

**Comment by hanju-java** [comment]
full note
file content：
<img width="1606" alt="image" src="https://user-images.githubusercontent.com/125666404/236788233-71c78c32-ca7a-46cf-b257-ce911150fd69.png">

**Comment by meld-cp** [comment]
Which version of the plugin are you using?

**Comment by hanju-java** [comment]
I updated the plugin once after I couldn't open the file
I guess it's 2.0.4

**Comment by hanju-java** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/125666404/236794359-65d6c691-a4b0-461a-8494-0fe457702295.png">

**Comment by meld-cp** [comment]
Do you mean you were on 2.0.4 then you updated it to the latest version?   Or are you running 2.0.4 now?

**Comment by hanju-java** [comment]
I was on 2.0.4 then updated it to the latest version this morning after file broken

**Comment by meld-cp** [comment]
Do you have any old backups of the encrypted file you can restore and try with?

You could also try rolling back to the old version of Obsidian and v2.0.4 of the plugin
