### ISSUE TITLE
Only the first text is previewed correctly for a list of encrypted texts.

### ISSUE THREAD

**Issue by yosuke-shinoda** [meld-cp/obsidian-encrypt#102]
Hi, @meld-cp.

I found a preview issue with "In-place Encryption".
Only the first text is previewed correctly for a list of encrypted texts.

**Source view**
<img width="541" alt="image" src="https://github.com/meld-cp/obsidian-encrypt/assets/57609568/f745a327-db4e-4800-90d3-85a2b5516f42">

**Preview view**
<img width="536" alt="image" src="https://github.com/meld-cp/obsidian-encrypt/assets/57609568/6eafbb82-3cf1-4d8e-b0ab-902d84b1bba8">

I hope this issue is fixed.
Thank you.

**Comment by solargate** [comment]
The same situation is for tables:

<img width="973" alt="image" src="https://github.com/meld-cp/obsidian-encrypt/assets/11595907/a9534039-f31e-4bb1-aabd-e165fd521a27">

<img width="970" alt="image" src="https://github.com/meld-cp/obsidian-encrypt/assets/11595907/f0c54960-c320-4f88-87c3-aa5ed0beeb35">
