### ISSUE TITLE
Find option doesn't work in the reading mode with encrypted notes

### ISSUE THREAD

**Issue by PolaricBear** [meld-cp/obsidian-encrypt#103]
I open the encrypted note.
I enter the password for decryption.
I can navigate through the note and edit it.
Search (Ctrl+F) doesn't work. There is no such line in the menu.

**Comment by meld-cp** [comment]
The `.encrypted` note editor is separate and independent from Obsidian's markdown editor, which makes it difficult to have a like-for-like editing experience between `.encrypted` and `.md` files.   Until there's a way to hook into the save-to/read-from disk api without corrupting notes, editing `.encrypted`  notes will be very limited.

Having said that, v2.3.0 adds the ability to quickly decrypt or encrypt an existing note (bind it to a hotkey).  So, the workflow could be to temporally decrypt the note to disk, edit it with all the nice Obsidian features, then re-encrypt it when done.
