### ISSUE TITLE
Cannot link to an encrypted file

### ISSUE THREAD

**Issue by EpicPilgrim** [meld-cp/obsidian-encrypt#104]
In Obsidian, once an encrypted note is created, I can not reference/link it from another file like [[Encrypted File]]. Firstly, autocomplete doesn't show the file. Secondly, Obsidian just creates a new blank .md file, rather than seeing the .encrypted file.

**Comment by meld-cp** [comment]
Hi @EpicPilgrim ,  there's a setting in Obsidian, see #59
