### ISSUE TITLE
How to create a new encrypted note in a specific folder?

### ISSUE THREAD

**Issue by Louisredstone** [meld-cp/obsidian-encrypt#106]
In some circumstances, I need to create a new note in a specific folder, like /Diary/ , /Management/ , etc.
I could do this when creating ordinary notes using QuickAdd. For example, click a quickadd command, select a folder in the prompt, then a note is created. But I didn't find a way to do the same when creating an encrypted note.
Someone knows any solutions? thanks.

**Comment by rhythmic1234** [comment]
Currently, we can only create an encrypted note under default note creation folder.
If we could create an encrypted file *under the path that is provided by user*, that would be very useful feature.
And we could ask the folder via a prompt.

By the way, I am using Templatr plugin, I can create files according to a specific template if the file is created under certain folder.
So it would be nice to use similar logic with Melt encrypt too, if we could create notes as encrypted automatically if they are under certain folder.

**Comment by GovSat1** [comment]
+1 some basic template/default options would be nice. A related (aesthetic) request would be to support .enc or a similar shorthand extension in addition to .encrypted. It is easy to modify the compiled JS to do this already, but it makes updates a bit of a pain.

**Comment by meld-cp** [comment]
from v2.3.6 you can right click a folder to create a note within it.
