### ISSUE TITLE
Indentation behaviour is broken

### ISSUE THREAD

**Issue by tiggerbiggo** [meld-cp/obsidian-encrypt#108]
meld version - v2.2.0 release
obsidian version - latest (v1.3.5)
platform - Windows 10 Enterprise 22H2
other plugins - none

In a secure note, trying to indent with TAB causes the interface focus to cycle, meaning I need to copy and paste indent characters to indent inside secure notes. I have confirmed that I can indent normal notes properly, it's only secure notes that have the issue.

Thanks for a very convenient and easy to use plugin, hope this is an easy fix :) won't stop me using it though

**Comment by meld-cp** [comment]
I had a quick look at this a few days ago and I ended up down a crazy parsing rabbit hole.

The `.encrypted` note editor is separate and independent from Obsidian's markdown editor, which makes it difficult to have a like-for-like editing experience between `.encrypted` and `.md` files.   Until there's a way to hook into the save-to/read-from disk api without corrupting notes, editing `.encrypted`  notes will be very limited.

Having said that, v2.3.0 adds the ability to quickly decrypt or encrypt an existing note (bind it to a hotkey).  So, the workflow could be to temporally decrypt the note to disk, edit it with all the nice Obsidian features, then re-encrypt it when done.

I'll leave this open as I think indenting is one of those basic features that should be included in the `.encrypted` note editor... when I figure out how
