### ISSUE TITLE
Offline Decryptor Tool Doesn't Seem to Work

### ISSUE THREAD

**Issue by rodrigolourencofarinha** [meld-cp/obsidian-encrypt#111]
I created a test note to try using the offline Decryptor Tool. However, it doesn't work. 

Can anybody confirm this issue?

Password: 123
Decrypted Text: "Test"

> {
> "version": "2.0",
>  "hint": "Password is 123",
>  "encodedData": "/nCpAPfr6v/EbLmLdW4VmzJC8HuF30a0ZmMlXq3YQOahx3Cd8V1XujyoPDkbzOk9McqRjA=="
> }

**Comment by meld-cp** [comment]
should be fixed in v2.3.0
