### ISSUE TITLE
Why the decrypt button disappeared? 

### ISSUE THREAD

**Issue by Cyletix** [meld-cp/obsidian-encrypt#113]
I can find the decrypting option a few months ago, but I don’t know when, I can only create encrypted note, is this related to the changes in Obsidian1.4?
![image](https://github.com/meld-cp/obsidian-encrypt/assets/45289906/1df00375-69a6-465e-b94f-8d2aae702dd3)

**Comment by Cyletix** [comment]
It show "unable to encrypt or decrypt that"
I found the reason, the line break before the lock icon 🔒 at the end of the encrypted text prevents decryption

**Comment by meld-cp** [comment]
Good spotting, I didn't notice that in your screenshot.  Glad you got it working 👍

**Comment by meld-cp** [comment]
Thanks @Cyletix ... I'll close this as I don't think it's a bug, any content between the markers should be left as is
