### ISSUE TITLE
Enable Outline

### ISSUE THREAD

**Issue by varpness** [meld-cp/obsidian-encrypt#114]
Per your suggestion to feature request specific things, I am wondering if it's possible to enable the Outline feature?

**Comment by meld-cp** [comment]
Thanks @varpness,

The `.encrypted` note editor is separate and independent from Obsidian's markdown editor, which makes it difficult to have a like-for-like editing experience between `.encrypted` and `.md` files.   Until there's a way to hook into the save-to/read-from disk api without corrupting notes, editing `.encrypted`  notes will be very limited.

Having said that, v2.3.0 adds the ability to quickly decrypt or encrypt an existing note (bind it to a hotkey).  So, the workflow could be to temporally decrypt the note to disk, edit it with all the nice Obsidian features, then re-encrypt it when done.
