### ISSUE TITLE
Shorcut to toggle reading/editing mode doesn't work inside encrypted notes

### ISSUE THREAD

**Issue by Cravtos** [meld-cp/obsidian-encrypt#116]
Pressing `cmd/ctrl+E` by default should toggle reading or editing mode, but in encrypted notes nothing happens. Considering there is no live mode in encrypted notes, having this hotkey working would be a very convenient feature.

**Comment by meld-cp** [comment]
Added to v2.3.2

A new command can be bound to your preferred hotkey (e.g. ctrl+e)
