### ISSUE TITLE
Change file-extension

### ISSUE THREAD

**Issue by eydun** [meld-cp/obsidian-encrypt#117]
Thank you for building this awesome plugin.

My backup-program wont backup files with the file-extension of ".encrypted". Is it possible to change the file-extension to something else?

**Comment by meld-cp** [comment]
@GovSat1 mentioned changing the extension too.

It's easy to do and I'm thinking of making the default extension `.mdenc`

I choose `.mdenc` because it fits in well with both, the plugin name '***m***el***d*** ***enc***ypyt' and the notion of '***m***ark***d***own ***enc***rypted'

**Comment by meld-cp** [comment]
Added to v2.3.2
