### ISSUE TITLE
encrypt whole note except frontmatter?

### ISSUE THREAD

**Issue by pictoys** [meld-cp/obsidian-encrypt#119]
I really like the icons you get on encrypted notes and when encrypting only a partial note i am worried to accidentally change the encrypted text. would be great to have that like when you encrypt a whole note all hidden. or an option to keep the frontmatter but encrypt the rest.

**Comment by meld-cp** [comment]
Hi @pictoys,

I don't think that's possible with how Obsidian works.

You are correct though, one could easily mistype into an in-place encrypted note and corrupt it.  This was the reason I added the whole-note encryption feature, but that has it's limitations too.

I would recommended using incremental backups, so you could roll back to a previous version if needed.
