### ISSUE TITLE
Encrypt a whole folder?

### ISSUE THREAD

**Issue by icedmoca** [meld-cp/obsidian-encrypt#121]
I'm wondering if this would be possible, this would be very useful for me. And if it has to be a zip thats okay aswell.

Edit: If implemented, I will sponsor. 
**If not implemented in the next three days, I will make my own plugin.**

**Comment by LiamSwayne** [comment]
#100

**Comment by meld-cp** [comment]
Wow, a 3 day deadline is really tough.

All the best with your new plugin, feel free to fork off this one if you like. 👍
