### ISSUE TITLE
Please provide an option to encrypt full pages in obsidian 

### ISSUE THREAD

**Issue by skillhacker-code** [meld-cp/obsidian-encrypt#13]
Please provide an option to encrypt full pages in obsidian  .

I don't need encryption ,just password protection so that no one who uses my computer can access a particular note , Kanban or mindmap

**Comment by knightlightdigital** [comment]
I would also love this capability, and would add that it would be awesome to encrypt files and folders. A use case would be for keeping a private journal inside a dedicated folder. Thank you for considering this!

**Comment by meld-cp** [comment]
> I also don't need password protection for folders or files. But an option in MELT ENCRYPT to encrypt the full text (without text-selection) within a note would be great.

Hi @702573n , could you create a new issue for encrypting whole notes please?

**Comment by meld-cp** [comment]
Thinking about this further, I could implement another command to encrypt the whole page.  But decryption will always be inplace and directly to disk.  Which means if you have any syncing of your vault running,  the decrypted file would also get synchronised.

It would be up to the user to manage this and make sure they remember to re-encrypt the page once they are done editing.

Would this still be useful?
