### ISSUE TITLE
Cannot see text at bottom of screen on Mobile

### ISSUE THREAD

**Issue by Sodapapi** [meld-cp/obsidian-encrypt#130]
I'm on Android and whenever I start typing on an encrypted note and reach towards the bottom, the text gets covered up by Obsidian's bottom toolbar. It won't let me scroll down more unless I decrypt the note.

Any way to fix this?

**Comment by meld-cp** [comment]
Hi @Sodapapi,
I think this is the same issue as #124, it will be fixed in the next release (most likely next weekend)
