### ISSUE TITLE
command line tool for encryption en decryption

### ISSUE THREAD

**Issue by MarcelBreuers** [meld-cp/obsidian-encrypt#131]
Obsidian-encrypt is already a great tool, but it would be helpful to have a node.js command line tool that can do encryption and decryption.  This helps when converting a bunch of encrypted notes from a different not taking application. I can see you have already browser based oflline GUI  tool for decryption offline-decrypt.js. So a command line tool would be easy.

**Comment by meld-cp** [comment]
dup of #105
