### ISSUE TITLE
Bug: Footnotes not displayed properly in reading mode when meld encrypt is enabled

### ISSUE THREAD

**Issue by mzietlow** [meld-cp/obsidian-encrypt#132]
Hi, 

I just noticed that footnotes are not correctly displayed when meld encrypt is activated.

For a minimal example, create a new vault, install meld encrypt and create a new file with the following content:

```md
Test[^1]

[^1]: Foot
```

When meld encrypt is active, the file contents will be displayed as

![image](https://github.com/meld-cp/obsidian-encrypt/assets/30702083/95ac4111-1711-411d-848f-bffeacbad739)

in reading mode.

Now, disable meld encrypt and reload Obsidian. The file contents will now correctly be displayed as 

![image](https://github.com/meld-cp/obsidian-encrypt/assets/30702083/ae9ddea6-004f-4bd0-a55b-149fed1d884c)

**Comment by dokmanc** [comment]
Same problem. 

I noticed that when I enable Meld, I get this:

nable to create popover: ref info not found in Map(8) {'fnref-5-9c3cb5c0c02c0a46' => {…}, 'fnref-6-9c3cb5c0c02c0a46' => {…}, 'fnref-7-9c3cb5c0c02c0a46' => {…}, 'fnref-8-9c3cb5c0c02c0a46' => {…}, 'fnref-9-9c3cb5c0c02c0a46' => {…}, …}[[Entries]]0: {"fnref-1-9c3cb5c0c02c0a46" => Object}1: {"fnref-2-9c3cb5c0c02c0a46" => Object}2: {"fnref-3-9c3cb5c0c02c0a46" => Object}3: {"fnref-4-9c3cb5c0c02c0a46" => Object}4: {"fnref-5-9c3cb5c0c02c0a46" => Object}5: {"fnref-6-9c3cb5c0c02c0a46" => Object}6: {"fnref-7-9c3cb5c0c02c0a46" => Object}7: {"fnref-8-9c3cb5c0c02c0a46" => Object}8: {"fnref-9-9c3cb5c0c02c0a46" => Object}9: {"fnref-10-9c3cb5c0c02c0a46" => Object}10: {"fnref-11-9c3cb5c0c02c0a46" => Object}11: {"fnref-12-9c3cb5c0c02c0a46" => Object}size: 12[[Prototype]]: Map
PopoverHandler @ plugin:better-fn:4026
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.clear @ app.js:1
t.clear @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-hover-editor:18
E @ plugin:obsidian-hover-editor:14
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
e.onInternalLinkClick @ app.js:1
o @ app.js:1
s @ enhance.js:1
plugin:better-fn:4026 Unable to create popover: ref info not found in Map(8) {'fnref-5-9c3cb5c0c02c0a46' => {…}, 'fnref-6-9c3cb5c0c02c0a46' => {…}, 'fnref-7-9c3cb5c0c02c0a46' => {…}, 'fnref-8-9c3cb5c0c02c0a46' => {…}, 'fnref-9-9c3cb5c0c02c0a46' => {…}, …}
PopoverHandler @ plugin:better-fn:4026
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.clear @ app.js:1
t.clear @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-hover-editor:18
E @ plugin:obsidian-hover-editor:14
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
e.onInternalLinkClick @ app.js:1
o @ app.js:1
s @ enhance.js:1
plugin:better-fn:4026 Unable to create popover: ref info not found in Map(8) {'fnref-5-9c3cb5c0c02c0a46' => {…}, 'fnref-6-9c3cb5c0c02c0a46' => {…}, 'fnref-7-9c3cb5c0c02c0a46' => {…}, 'fnref-8-9c3cb5c0c02c0a46' => {…}, 'fnref-9-9c3cb5c0c02c0a46' => {…}, …}
PopoverHandler @ plugin:better-fn:4026
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.clear @ app.js:1
t.clear @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-hover-editor:18
E @ plugin:obsidian-hover-editor:14
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
e.onInternalLinkClick @ app.js:1
o @ app.js:1
s @ enhance.js:1
plugin:better-fn:4026 Unable to create popover: ref info not found in Map(8) {'fnref-5-9c3cb5c0c02c0a46' => {…}, 'fnref-6-9c3cb5c0c02c0a46' => {…}, 'fnref-7-9c3cb5c0c02c0a46' => {…}, 'fnref-8-9c3cb5c0c02c0a46' => {…}, 'fnref-9-9c3cb5c0c02c0a46' => {…}, …}
PopoverHandler @ plugin:better-fn:4026
t.postProcess @ app.js:1
t.postProcess @ app.js:1
h @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.onRender @ app.js:1
requestAnimationFrame (async)
dt @ app.js:1
e.queueRender @ app.js:1
e.clear @ app.js:1
t.clear @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-hover-editor:18
E @ plugin:obsidian-hover-editor:14
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openLinkText @ app.js:1
e.onInternalLinkClick @ app.js:1
o @ app.js:1
s @ enhance.js:1

**Comment by meld-cp** [comment]
Thanks for reporting.  A fix is in the `next` branch which will be released soon.

**Comment by dokmanc** [comment]
I just received a new version of Meld Plug in, version 2.34, and I still have the issue where enabling the Meld plug-in causes the Better Footnotes to stop displaying pop up tool tips. For example:


`Some text followed by a popup tooltip: ^[test tooltip]`
