### ISSUE TITLE
Meld Encrypt + Code Styler breaks codeblocks

### ISSUE THREAD

**Issue by Aetherinox** [meld-cp/obsidian-encrypt#133]
Hey. I love this plugin, it is one of my top used. However, the plugin [Code Styler](https://github.com/mayurankv/Obsidian-Code-Styler) is also one of my top used.

When Meld Encrypt is installed, the formatting for the Code Styler plugin breaks completely. The issue is I'm not sure if it's coming from your end, or if Code Styler did something.

I went through and did a quick peak at the CSS to see if it was a simple CSS fix, but the CSS isn't causing it. So I'm assuming it has to do with showing an encrypted note in **Reading Mode**.

Edit Mode appears fine, but as soon as I flip over to Reading Mode, the code block breaks.

### Meld Encrypt Disabled
![W0VY2o8](https://github.com/meld-cp/obsidian-encrypt/assets/118329232/68acb20d-0b76-4d7d-a254-e397e685ce54)

### Meld Encrypt Enabled
![PDvPFmr](https://github.com/meld-cp/obsidian-encrypt/assets/118329232/37ad38a9-8700-48c5-b96b-6aef25e6c4de)

If you want to take a quick look and see if it's a simple thing, or I can try to drop a ticket over at the other guy. As I said, not sure which side it's coming from, but hopefully it's a simple solution as I love both these plugins.

Another thing to note, disabling Meld doesn't fix or start the problem. If you have Meld enabled when Obsidian starts up, the issue shows. But you'd have to disable meld and completely restart Obsidian before the issues goes away.

**Comment by meld-cp** [comment]
Thanks @Aetherinox, I'm pretty sure it's related to #132 ... My fault 😬... But it should be fixed in the next release (hopefully this weekend)

**Comment by meld-cp** [comment]
Should be fixed in v2.3.4, will reopen if not
