### ISSUE TITLE
Checkboxes broken when using source mode and editing view

### ISSUE THREAD

**Issue by marc-alexis-com** [meld-cp/obsidian-encrypt#134]
Hi ! 
First time writing an issue on Github, I'm a little bit nervous, but I will do my best.

Recently, I've experienced issues with my checkboxes in Obsidian, after some experimentation, I've narrowed the problem to the Meld Encrypt plugin that I use daily.

Only while using theses settings : 

![CleanShot 2023-11-03 at 14 26 04](https://github.com/meld-cp/obsidian-encrypt/assets/149798617/80920ff5-01a0-471e-86c4-f0a7895a3739)

Does the checkboxes not update after going back to edit mode.

(Tried on a completely new vault with only Meld Encrypt and theses settings changed)

1. Source mode : 

![CleanShot 2023-11-03 at 14 28 03](https://github.com/meld-cp/obsidian-encrypt/assets/149798617/9c4dba52-2d86-49ac-9608-4448d88f19ab)

2. Clicking on the checkboxes in source mode :

![CleanShot 2023-11-03 at 14 28 16](https://github.com/meld-cp/obsidian-encrypt/assets/149798617/7442ccb1-bd92-4b3e-8817-a97563e8b50c)

3. After going back to edit mode :

![CleanShot 2023-11-03 at 14 28 28](https://github.com/meld-cp/obsidian-encrypt/assets/149798617/9e0e5df4-4678-4dae-98b8-cd50d264a877)

**Comment by meld-cp** [comment]
Hi @marc-alexis-com, thanks for reporting the issue.  No need to be nervous, you did well.

I think the the issue you reported was related to #132.

I've released a new version today which hopefully fixes the problem you are seeing as well. 🤞
