### ISSUE TITLE
Enabling the plugin makes footnotes not work anymore.

### ISSUE THREAD

**Issue by aikooo7** [meld-cp/obsidian-encrypt#135]
I started having problems with footnotes, enabling plugins one by one I found that it meld encrypt that "destroys my footnotes".

# Before activating plugin

![image](https://github.com/meld-cp/obsidian-encrypt/assets/79667753/77e735f8-ffd5-416a-b7a3-b231436a161e)

# After activating the plugin

![image](https://github.com/meld-cp/obsidian-encrypt/assets/79667753/e14f04df-e3e1-4b6c-90de-1c7c71b6e8d6)

**Comment by meld-cp** [comment]
Try v2.3.4

**Comment by aikooo7** [comment]
First of all, sorry for making a duplicate of #132 , I didn't do the proper search I should do.
Second, it works now thanks a lot!
