### ISSUE TITLE
Enabling the plugin makes dataview not work anymore

### ISSUE THREAD

**Issue by Shidiq** [meld-cp/obsidian-encrypt#136]
I started having problems with dataview & todoist plugin in Reading Mode

### Editing Mode

![CleanShot 2023-11-04 at 06 57 41@2x](https://github.com/meld-cp/obsidian-encrypt/assets/23032122/0cb70497-d823-47f1-96b1-27f417c18063)

### Reading Mode

 
![CleanShot 2023-11-04 at 06 59 04@2x](https://github.com/meld-cp/obsidian-encrypt/assets/23032122/0af21c09-24e0-4f0d-b557-993c499cbe9c)

**Comment by meld-cp** [comment]
Try v2.3.4

**Comment by Shidiq** [comment]
I'm currently install v2.3.4

![CleanShot 2023-11-04 at 07 21 42@2x](https://github.com/meld-cp/obsidian-encrypt/assets/23032122/35eb7ba3-2819-497c-8e74-1bc4c0f6f157)

**Comment by meld-cp** [comment]
Hmmm, could you try uninstalling the plugin and reinstalling it?

Failing that can you send me a minimal example so I can try to reproduce the issue?

**Comment by Shidiq** [comment]
Mmm... not work in my setup (still same issue after uninstall and reinstall)

Just regular dataview code:

```md
---
week: '[[2023-W44]]'
month: '[[2023-11]]'
year: '[[2023 Year Plan |2023]]'
---
[[2023-11-03|«]] [[2023-11-04|Saturday]] [[2023-W44|4]] [[2023-11|Nov]] [[2023 Year Plan|2023]] [[2023-11-05|»]]

## ⁜ Saturday - November 4th 2023

> [!quote]
> In three words I can sum up everything I've learned about life: it goes on.
> — <cite>Robert Frost</cite>

---

> [!todo] Daily Quests
> ```todoist
> name: –––––––––––––––
> filter: "(#Inbox & no date) | today | overdue"
> sorting:
> - date
> - priority
> group: true
> ```

> [!example] On This Day...
> ```dataview
> TABLE file.cday as Created, summary as "Summary"
> FROM "/" where contains(file.outlinks, [[2023-11-04]])
> SORT file.cday DESC
> ```

## ⁜ Memos

```

**Comment by Asetnozama** [comment]
I can confirm. Latest update messed up dataview and the task plugin.

**Comment by marc-alexis-com** [comment]
I confirm too, tried everything.

**Comment by meld-cp** [comment]
Hi,

Could someone please confirm if v2.3.5 fixes this issue?

**Comment by Shidiq** [comment]
Just a quick note to express my gratitude for your swift bug-fixing skills. Thank you...

**Comment by meld-cp** [comment]
Thanks @Shidiq , I'm glad it's working again.
