### ISSUE TITLE
Should encrypted notes be read only?

### ISSUE THREAD

**Issue by MaikoID** [meld-cp/obsidian-encrypt#137]
Hello!

I realized that if one changes the encrypted text by mistake is impossible to decrypt it afterwards and one can lose precious information. 
To avoid that seems reasonable to opt to have your encrypted notes read-only somehow, perhaps on the file system itself?

Thanks!

**Comment by meld-cp** [comment]
Do you mean read-only within '.md' or '.mdenc' notes?

**Comment by meld-cp** [comment]
It uses the normal Obsidian editor and I don't think I have control over which characters are editable.. so, yes be careful and have backups
