### ISSUE TITLE
Adding option to change "Editing an encrypted note" text 

### ISSUE THREAD

**Issue by LeoCodesss** [meld-cp/obsidian-encrypt#138]
I know it's quite nitpicky but boy do I hate the emojis used. I would like a text field where you can write your own text or leave empty for disabling the text completely.

**Comment by ChaoticCyber** [comment]
![changeemojitest](https://github.com/meld-cp/obsidian-encrypt/assets/20806827/b6994e80-5428-4d31-ab04-b28b9387f222)

If you want to change the emojis you can just change the unicode emojis in the ".obsidian\plugins\meld-encrypt\main.js" file. If you'd like to get rid of it completely you can remove everything in that curly brace section, reload and it's gone.

**Comment by LeoCodesss** [comment]
Thanks that did the trick
