### ISSUE TITLE
Will the encrypted note being stored decrypted in vault due to Obsidian caching?

### ISSUE THREAD

**Issue by mrhalf** [meld-cp/obsidian-encrypt#139]
Hi team, 

I really love this plugin which enables an end-to-end encryption experience.  Reading thru the source code, looks like the notes are always encrypted before saving to disk within this plugin's scope. However I wonder if Obsidian's would cache decrypted documents on disk or in vault while editing or previewing?  

Would really apprecaite if you can help me understand this matter. 

Thanks,

**Comment by meld-cp** [comment]
Not that I'm aware of.

**Comment by mrhalf** [comment]
Thanks for the clarification. im going to close this out then
