### ISSUE TITLE
[Question / Bug]: Cancelling GPG passphrase freezes page

### ISSUE THREAD

**Issue by Aetherinox** [meld-cp/obsidian-encrypt#141]
Hey,

I'm not sure if this is a bug, or unavoidable behavior by GPG, but it definitely has something to do with Obsidian.

A few days ago I created a note, `test.md`. I had opted in the settings for a note to be .gpg instead of .md, so test.md became `test.gpg`.

I let that note sit for a few days and decided to mess around with this plugin today, and just for testing purposes, I wanted to see what would happen if I clicked on the note to open it, but then cancelled the GPG prompt to enter my passphrase.

Once I clicked cancel, Obsidian will not allow me to click on any other note at all. All it does is just bring up a Obsidian notification which is the typical GPG error about cancelling the operation.

It will let me re-click on the note I originally tried to open and it prompts me for my passphrase again, but clicking cancel starts to loop all over. I can't click on any other note to open it until I actually click on that note and enter the passphrase.

Keeping in mind that the note I clicked cancel on is the only note in the vault encrypted. The rest are not and are just standard .md files.

I can however, open a new tab and start navigating around again, but I'd have to close the original tab because it's now useless unless I actually enter that passphrase.

**Comment by meld-cp** [comment]
hi @Aetherinox did you log this in the wrong plugin repo?

**Comment by Aetherinox** [comment]
Jesus..... I have your plugin installed and the GPG encryption plugin.

Yeah, that was my bad. I only have yours starred. Not the other. The holidays are starting to mess with my brain already.

Sorry lol

**Comment by meld-cp** [comment]
Ha, all good mate 😊👍
