### ISSUE TITLE
[FR] Insert the ciphertext directly to the note

### ISSUE THREAD

**Issue by ckdanny** [meld-cp/obsidian-encrypt#143]
Context:

> Obsidian Sync will keep the version history up to a year. Encrypting a small part of content in the note cannot erase it from the revision history.

Proposed solution:

> Allow a prompt to let the user input the content and directly insert the encrypted text into the note. This way, the version history will not keep the plaintext.

**Comment by meld-cp** [comment]
good idea @ckdanny

**Comment by meld-cp** [comment]
from v2.3.6 if you invoke the Encrypt/Decrypt command with no text selected, you will get a dialog with a section to enter the text to encrypt directly into the note
