### ISSUE TITLE
Internal links not working in an encrypted note

### ISSUE THREAD

**Issue by ilcecca** [meld-cp/obsidian-encrypt#144]
Hi!
I've tried to link some text in an encrypted note to a note in my vault but apparently is not working.
I've tried the following markdown codes:
`[[path/to/my/notename.md|notename]]`
and
`[[notename]]`
In both cases the text appear as a link but is not clickable.
My fault or this is not (yet?) available in an encrypted note?
Can you suggest me a workaround in case is not possible to link to another note?
Thanks in advance!

**Comment by meld-cp** [comment]
Hey @ilcecca, yeah, not implemented yet.  It should work in the next version, just doing some testing now.

**Comment by ilcecca** [comment]
Thanks a lot for your work and the prompt reply! I'll wait the next version and, for the time being, I'll stay with an encrypted vim file (and try to learn vim in the meantime :) )

**Comment by meld-cp** [comment]
Hi @ilcecca, this should be working in reading mode in the latest release (v2.3.6)
