### ISSUE TITLE
make editing view render markdown elements like (lists) in editing mode

### ISSUE THREAD

**Issue by kabooHD** [meld-cp/obsidian-encrypt#151]
using the plugin in editing view I am unable to render lists the same way in reading view:

![image](https://github.com/meld-cp/obsidian-encrypt/assets/79645612/788093a5-c8d9-4f16-ab6d-6f2f9704d0ef)

while in reading view I can view elements:

![image](https://github.com/meld-cp/obsidian-encrypt/assets/79645612/cd39d120-6a59-4bb9-9271-607f189071aa)

but for non encrypted notes I can both edit and view the result of my editing (render lists ...) in the editing view

![image](https://github.com/meld-cp/obsidian-encrypt/assets/79645612/f5c7632c-fb16-4bcc-be36-63e6790cf782)

**Comment by paradeiser** [comment]
This would be great and make the experience much better.
Are there any chances this will come in the future?

**Comment by meld-cp** [comment]
Yeh, it was a limitation of the editor view I was using... I have been working on an update...

Please make a backup of your vault and test [v2.4.0-beta](https://github.com/meld-cp/obsidian-encrypt/releases/tag/2.4.0-beta) if you can.
