### ISSUE TITLE
[BUG] v2.4.0.beta - Decrypted data is written to disk

### ISSUE THREAD

**Issue by meld-cp** [meld-cp/obsidian-encrypt#164]
While trying to find some kind of file IO related bug in 2.4.0, I accidently found a bug that decrypted data is written in disk when "Save current file(Ctrl-S)" is performed multiple times rapidly.

I wrote a simple GO program that reads and prints `test.mdenc` whenever it changes. Below is the result I got by repeatedly pressing Ctrl-S.

![image](https://github.com/meld-cp/obsidian-encrypt/assets/43294688/d27948e6-a3b9-415d-b011-80670b40c8e8)

![image](https://github.com/meld-cp/obsidian-encrypt/assets/43294688/6f63ca95-9307-4a50-a184-997caf586b07)

```go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/fsnotify/fsnotify"
)

func onChange() {
	data, err := os.ReadFile("test.mdenc")
	if err != nil {
		panic(err)
	}
	fmt.Println(string(data))
}

func main() {
	w, err := fsnotify.NewWatcher()
	if err != nil {
		panic(err)
	}
	defer w.Close()
	go func() {
		for {
			select {
			case e, ok := <-w.Events:
				if !ok {
					return
				}
				if e.Name == "test.mdenc" {
					onChange()
				}
			case err, ok := <-w.Errors:
				if !ok {
					return
				}
				log.Println("error:", err)
			}
		}
	}()
	err = w.Add(".")
	if err != nil {
		panic(err)
	}
	<-make(chan struct{})
}

```

* 2.4.0-beta.2
* Windows 11
* No extra io related factors (e.g. Google Drive or antivirus)

_Originally posted by @wirekang in https://github.com/meld-cp/obsidian-encrypt/issues/163#issuecomment-2156077549_

**Comment by meld-cp** [comment]
Hi @wirekang, [v2.4.0-beta.3](https://github.com/meld-cp/obsidian-encrypt/releases/tag/2.4.0-beta.3) should fix this issue.

**Comment by wirekang** [comment]
Great. I can't reproduce the bug in 2.4.0-beta.3.
