### ISSUE TITLE
Improve 'decrypt' function when 'Expand selection to whole line' is disabled 

### ISSUE THREAD

**Issue by therden** [meld-cp/obsidian-encrypt#27]
At present, if the 'Expand selection to whole line' option is disabled, then one has to select the entire encrypted text (including the bracketing doubled %s) -- otherwise the **Meld Encrypt** commands don't appear in the Command Palette.[^1]

It would be better if, when the keys to bring up the Command Palette were pressed, the plug-in 
1) detected when the cursor was located within a block of encrypted text, 
2) selected that block of encrypted text, and _then_ 
3) brought up the Command Palette.

[^1]: I see that this previously was referenced in the following comment in a now-Closed issue: https://github.com/meld-cp/obsidian-encrypt/issues/20#issuecomment-952701683

**Comment by meld-cp** [comment]
fixed in v1.5.2

**Comment by therden** [comment]
Thank you!  This much- improved functionality -- and the support for password hints -- have inspired me to nominate **Obsidian Encrypt** as a ['Gem of the Year'](https://forum.obsidian.md/t/obsidian-gems-of-the-year-2021-nomination-plugins/28224/28).

**Comment by meld-cp** [comment]
No problem, it was a good idea.  Thanks for your support too 👍
