### ISSUE TITLE
Add support for password hints

### ISSUE THREAD

**Issue by therden** [meld-cp/obsidian-encrypt#28]
Thank you for making and sharing this plug-in.

Please consider adding support for optional **password hints** that are saved at encryption time and then presented to the user when encrypted text is selected for decryption.

By _reducing_ the risk of being unable to recall the password required to decrypt a block of text, **password hints** would _encourage_ users to employ as many different encryption passwords as make sense in their use-case.

**Comment by meld-cp** [comment]
That's a good idea 👍

**Comment by therden** [comment]
Password hints work great -- _thank you_ for implementing them!
