### ISSUE TITLE
Change Decrypted Text Inside The Small View Container

### ISSUE THREAD

**Issue by 702573N** [meld-cp/obsidian-encrypt#32]
I like to encrypt my whole notes and show the decrypted text inside the small preview-container. On this way the synced notes can't be synced decrypted and all my notes are safe. Unfortunately there is no way to edit the decrypted text inside the small preview-container and push the new encrypted text to the original note. Any chance to realize that?

Oh. One more thing. Any chance to optimize the size of the small preview-container? I would like to make it bigger on obsidian desktop only.

**Comment by meld-cp** [comment]
Please check version v2.0.0 and see how you get on with the new standalone encrypted note setup.
