### ISSUE TITLE
 Is it possible to decrypt without obsidian? If so, how?

### ISSUE THREAD

**Issue by Fertion** [meld-cp/obsidian-encrypt#37]
Is it possible to decrypt without obsidian? If so, how?

I used many different online services to try to decrypt, but whatever settings I chose, they did not fit.

**Comment by meld-cp** [comment]
Hi @Fertion,

It's possible but you'd have to use the code in the plugin.

See: CryptoHelper.ts

There's no end user tool to do it (apart from Obsidian itself)
