### ISSUE TITLE
Android: Meld Encrypt commands missing from command palette 

### ISSUE THREAD

**Issue by mrpurplecloud** [meld-cp/obsidian-encrypt#38]
Android 11/12
Obsidian 1.1.1/1.2.0
Meld Encrypt: 1.6.2
Android System WebView: 99.0.4844.88

Couldn't find any Meld Encrypt commands when typing meld or crypt in the command palette.

However it works fine on an older phone which has Android 10 and Android System WebView 98.0.4758.101. 

I had similar problem with some other plugin before which turned out to be compatibility issue with WebView, so I provided its version number above hoping it could be useful to troubleshooting.

**Comment by meld-cp** [comment]
Hi @mrpurplecloud,

I'll try to have a good look at this over the weekend.

My initial findings are that it works for me with the same version of WebView, Android 12, Obsidian 1.2.

I selected text, then brought up the command pallet using the icon from the ribbon bar on the left, then searched for meld.

Is it possible to send a gif or something with what you are trying/seeing?

**Comment by mrpurplecloud** [comment]
Greetings. I tried to record a gif but was unable to reproduce the issue today. The encrypt commands just magically appeared. I guess it might be related to Obsidian's command indexing process but have no evidence. Please close the issue for now. Thanks for your time!
