### ISSUE TITLE
Feature request: add command to encrypt/decrypt all files in a folder

### ISSUE THREAD

**Issue by lucabello** [meld-cp/obsidian-encrypt#39]
Hi! First of all, this is a great Obsidian plugin!

I find myself in the common use case of having a journal in Obsidian which I would like to encrypt. Cryptomator falls short for me because 1. I don't sync my journal automatically and 2. I would like to access it from mobile as well.

The ideal functionality for me would be having a command in the palette which, given a folder, encrypts/decrypts all the files in the folder (and the subfolders). So, it would act on ALL Markdown files found by récursively navigating that folder. It's a very similar thing to what the command "Encrypt a whole file" does, except you would specify a folder instead.

I have no need for automation or more complexity, I would just like to:
1. Open Obsidian
2. Palette -> Decrypt files in folder -> Insert password
3. Use my journal
4. Palette -> Encrypt files in folder -> Insert password

If I forget to re-encrypt files, that's on me :)

What do you think about having this feature? I'm open to create a PR myself if you are busy with other things, but first I'd love to hear your thoughts

Cheers!

**Comment by lucabello** [comment]
Actually, I had a look at the code and saw that for how it's structured, it's not a straight-forward change. I implemented the functionality already, so it's more of a question if you'd like to have this functionality in your plugin, or if you wouldn't mind me forking this repo to make a different plugin which only has the "Encrypt Whole Folder" functionality !

**Comment by meld-cp** [comment]
Hi @lucabello, I'm having trouble finding the time to support the basic functionality of the plugin as it stands now 🙂.  So, yes, I think for now if you could please fork it? 

I have an idea I'd like to explore which would always have the notes encrypted on disk but will still allow you to edit on desktop and mobile.   I think this would make for a better experience and would help with your issues above.  I'll slowly get there. 🙂

**Comment by lucabello** [comment]
Understandable, will do as you say then!

Will patiently wait for the new feature, keep up the great work! :D

**Comment by cryptochiggy** [comment]
If I was a physiatrist, with a vault called CLIENTs, with notes titled as each respective client's NAME.... anybody with physical or network access to the local drive/files could openly see sensitive data.

One should be able to encrypt the entire VAULT. Or, maybe just the CLIENT folder specifically , and all its contents recursively. It would be nice if either the entire VAULT, FOLDERS, SUBFOLDERS could be selected to auto encrypt/decrypt via some menu too. Seems to me this would work on mobile too.

**Comment by lucabello** [comment]
I actually ended up modifying this plugin for that purpose exactly, since (as you can infer from the comments on this issue) this project might took a slightly different direction!
I use it to encrypt the folder containing my journal notes :)

I was busy with other stuff, but I will soon (probably in the coming month) publish a fork of this project so you can use that too; hold tight, it's coming!
