### ISSUE TITLE
Single common password

### ISSUE THREAD

**Issue by jtmusky** [meld-cp/obsidian-encrypt#4]
Idea of using a single password to lock and unlock a master encryption key. Possibly use an ".obsidian.meld" file that has an encrypted master password key. You can use a password to unlock the master key that is used to encrypt/decrypt content within obsidian..

**Comment by meld-cp** [comment]
I'm not sure I follow.   This is so you don't need to keep typing in the password for each block of encrypted text?

How about the last password entered persists in the password dialog?   You wouldn't need to retype the password for that vault session (or maybe have a timeout, say 1hr).   This would speed up encrypting/decrypting blocks if you tended to use the same password.

**Comment by jtmusky** [comment]
Yeah, I'm not sure if I expanded on that thought very well. 

Basically having two keys. The first (data Encryption) key is generated by meld, then meld can ask the user for a password that would then encrypt the data encryption key and place it into a file called .obsidian.meld. The content is actually encrypted with the data encryption key. The user is only prompt for a password to decrypt the data encryption key (to be held in memory) to encrypt/decrypt the content. 

Does that make more since? It was late when I writing this concept up.

**Comment by meld-cp** [comment]
Thanks @jtmusky that is clearer.  But I'm not sure of the value of having 2 keys.  You could try the 'remember password' option I've just added in 1.3.0 along with the encrypt-in-place command.  Maybe this works better for your use case?

**Comment by jtmusky** [comment]
The value would be to store the password with the vault, possibly even within git "encrypted". I would suggest using PBKDF2 as the encryption cipher with some sort of salt. I'll try 1.3.0

**Comment by meld-cp** [comment]
Thanks!  If you store your key with the vault, wouldn't that be a security risk?  If your vault was compromised, so would your key and your secrets, right?  Someone with access to your vault would be able to use your key.  And if the key was password protected, and you had to enter the password before use, then you're not really gaining anything because you need to enter a password anyway.  I feel like I'm missing something 🤔

**Comment by jtmusky** [comment]
Trying release 1.3.0 with the "remember" password option does work well.

Another value is being able to change the password, with out re-encrypting all the data within the vault.

**Comment by barbwire08** [comment]
I've just installed Meld Encrypt Version: 1.3.1 into Obsidian but when I complete Step 2 "Enter and confirm a password to use" my selected text doesn't encrypt. 
i.e. After entering my password into the "Enter your password" box and tabbing to the"Confirm your password" box to re-enter my password, I hit enter, but the text doesn't encrypt. 
Does my password have to be a certain length or contain a mix of numbers and letters? I much appreciate your help. Thank you.
![image](https://user-images.githubusercontent.com/81460986/112713921-db448a80-8f2b-11eb-891a-441fa4214fae.png)

**Comment by jtmusky** [comment]
Just tested, I was able to use " " a space to encrypt. I don't think there is a minimal password strength.

**Comment by meld-cp** [comment]
@jtmusky is correct, there isn't any length or complexity requirements for passwords.

I'm not able to reproduce the issue you are having.  Which operating system are you using?  Is it possible to record a gif or video of the issue?  Having that usually helps a bunch to track down and fix bugs.

**Comment by barbwire08** [comment]
https://user-images.githubusercontent.com/81460986/112741188-18ae2400-8fcf-11eb-87d7-b968a575ff9a.mp4

I am using Windows 10 operating system. 
I would like to confirm that I should hit enter after the last step of inputting my password in the "confirming my password" box for the text to be encrypted.
Thank you very much.

**Comment by meld-cp** [comment]
@barbwire08 yes, correct, you should be able to enter your password, hit Return, reenter your password to confirm, then hit Return again to encrypt your text.   Does it work like this for you?

**Comment by barbwire08** [comment]
No it doesn't work like that for me. I enter my password and hit the *Tab *key
for the curser to move down to the "Confirm your password" box as the
Return key doesn't work, then I reenter my password to confirm, but when I
hit Return nothing happens - the password box doesn't disappear from my
screen until I click outside the password box and the text has not been
encrypted.  I have attached another video FYI.
Thank you

**Comment by meld-cp** [comment]
Let's track this in another issue as it's unrelated to the original (https://github.com/meld-cp/obsidian-encrypt/issues/7)

**Comment by meld-cp** [comment]
Hi @jtmusky, sorry, but I don't think the original request fit's in with how the plugin is designed and to be honest I'm not completely sure I'll be able to implement what you are wanting anyway, so I'll close this issue.  Thank you for your donation and the time you've given testing the plugin.

**Comment by jtmusky** [comment]
I understand. TBH, a better way to ensure confidentiality would to use an FDE or encrypted volume. Thank you for considering. :-)
