### ISSUE TITLE
Larger File is not able to be encrypted

### ISSUE THREAD

**Issue by L00tz1ffer** [meld-cp/obsidian-encrypt#41]
Got a File with 21k words. tryin to encrypt file but file does not get encrypted, is there a limit for purpose?!

**Comment by meld-cp** [comment]
Tracking down the issue to:
```
EncryptedFileContentView.ts:230 RangeError: Maximum call stack size exceeded
    at CryptoHelperV2.eval (CryptoHelper.ts:59:35)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73:58)
```

which is this line
```ts
//convert array to base64
const base64Text = btoa( String.fromCharCode(...finalBytes) );
```

will work on a fix

**Comment by meld-cp** [comment]
I suspect the error is to do with the `String.fromCharCode` call.

To workaround the problem I'll need to batch the calls to `String.fromCharCode` and concatenate the results.
