### ISSUE TITLE
Picture encryption

### ISSUE THREAD

**Issue by sfdrada** [meld-cp/obsidian-encrypt#42]
Could it be possible to embed encrypted data into a picture/link in obsidian. My idea is to click on a picture and then decode it (hopefully including the [[]] external brackets) to get access to the data.

Thanks for the support!

**Comment by meld-cp** [comment]
Hi @sfdrada,

Do you mean something like whats implemented here?: https://github.com/computationalcore/cryptosteganography


I.e. Hide encrypted text in an image, but the image is still viewable.

Anyone looking at the image wouldn't know that it had a secret inside it.
