### ISSUE TITLE
Keep session password stored for subsequent encryptions as potential default

### ISSUE THREAD

**Issue by Gewerd-Strauss** [meld-cp/obsidian-encrypt#43]
Currently, the password can be kept for decryption for a time period which can be set in the plugin options.

I would like to ask that during a session, once you use a password for encryption, to give the same password for encryption upon subsequent attempts at encrypting further blocks/files. Then the user can either continue each encryption with the same password, or clear the fields and enter a new one.

When obsidian closes, that cache is cleared and during the next session the first encryption attempt has no preset password again. Every encryption thereafter within the same session uses the password used during the first encryption as its optional default.

**Comment by meld-cp** [comment]
Hi,

Please test with v2.0.3, there have been a few changes with how passwords are handled and remembered.

**Comment by Gewerd-Strauss** [comment]
Thank you for the update - this resolves my issue. Thank you.
