### ISSUE TITLE
Don't break the backward compatibility

### ISSUE THREAD

**Issue by skywind3000** [meld-cp/obsidian-encrypt#46]
Selection text encryption is very handy, it is once a killing feature in EverNote

If you do want to change direction of this project: could you please at least keep the old functionality ??

Some times, I only have a small part of text to encrypt, like my online gaming accounts, it is not so important which need a strong encryption method.

It is convenient to keep them in an unencrypted note, with plain text beside describing what it is and how to use it.
But the whole document encryption requires me to enter the password before knowing what is in there.

Selection encryption and whole document encryption does not conflict with each other. no need to drop one.

If you do have an new direction, why not create a new plugin ?

Or at least keep the compatibility for 1.x.

**Comment by meld-cp** [comment]
🤔 I was really looking forward to removing all that old code. 

The comment style encryption was becoming a pain to maintain and also causing a few issues with people accidentally corrupting the encryption and losing their content.

Have you tried creating a link to the .encrypted note?  May be this would work just as well for you?

E.g. your note could look something like:
```
...
Sensitive text for my account can be found here: [[my secret account file.encrypted]]
...
```

Maybe that workflow won't be so bad?

**Comment by skywind3000** [comment]
Could you please start over in a new project ??
or move the classic functionality into a `meld-encrypt-classic` project ??

If you are too busy, I can maintain a classic fork for you.

**Comment by skywind3000** [comment]
I have temporarily created a legacy fork:

https://github.com/skywind3000/meld-encrypt-classic/

For those who want the classic selection encryption functionality like me,  
can install this fork with [obsidian-brat](https://github.com/TfTHacker/obsidian42-brat).

**Comment by earlsab** [comment]
I agree with keeping old functionality, there's way too many notes that is already partially encrypted. If you're worried about users corrupting their own data perhaps a opt-in toggle switch can be added instead with a quick little warning pop-up or something.

Personally, I encrypt only parts of my **daily** notes for an extra layer of security. (i.e. Preventing people who have access to my laptop in reading my personal notes). But at the same time, I want other parts to be easily readable if I want to access them quickly and refer back to them.

I think the encrypt file feature is fantastic for other applications where it involves critical data you don't want to be accidentally corrupted. But for casual use cases like mine, I would prefer something quick and easy.

**Comment by meld-cp** [comment]
Thanks @skywind3000 and @earlsab for your use cases. 

Out of curiosity, do you use the feature more for obfuscation or encryption? 

Obfuscation wouldn't need a password, which would simplify it a bit.   And it may be possible to do things like click or hover to reveal etc.

In any case, my aim is to review the code this weekend and see if this feature can be simplified and made more maintainable.

**Comment by arnmac** [comment]
I personally use the inline encryption to ensure that the data is not stored unencrypted at rest. Obfuscation alone is not my intent.

**Comment by meld-cp** [comment]
Apparently, I'm a sucker for punishment and I'm gonna do a 180 and keep it in.

I've refactored the code a bit to isolate the features and it should be easier to manage going forward.   And I'll probably need to add a warning about how easy it is to corrupt the in-place encryption (simple mistype for instance)

I'll push a release tomorrow.   Thanks for the feedback 👍

**Comment by earlsab** [comment]
> Out of curiosity, do you use the feature more for obfuscation or encryption?

Thanks for considering this! Regarding your question, I write my daily personal notes/thoughts using obsidian. I just like the peace of mind knowing that no one can or will be able to read it (even if ever I leave my laptop unlocked). 

Because the notes are daily, I don't really mind the risk of corrupting the data as I don't usually open that day's notes often if at all, but could be useful for me as a sort of time-capsule (nothing too serious).

**Comment by meld-cp** [comment]
fixed in v2.0.2

**Comment by skywind3000** [comment]
Thanks for it.

**Comment by therden** [comment]
Even with the terrific new features and UI improvements that you've recently made to the plugin, dropping support for encrypting/decrypting selected text would have been a significant loss for me.

Thank you _very_ much, @meld-cp, for restoring it!

Time for me to give you another coffee...
