### ISSUE TITLE
Markdown inside encrypted notes

### ISSUE THREAD

**Issue by meld-cp** [meld-cp/obsidian-encrypt#48]
> Please check version v2.0.0 and see how you get on with the new standalone encrypted note setup.

OK honeymoon's over.
Can we have Markdown inside encrypted note? 🙏🙏🙏 pretty pretty pretty please?

_Originally posted by @mardoqueo in https://github.com/meld-cp/obsidian-encrypt/issues/31#issuecomment-1305585083_

**Comment by meld-cp** [comment]
That was the initial intent, and would be awesome, but unfortunately, I ran into corruption issues with my implementation when switching between markdown views (reading, edit, source, live preview etc).

So we are stuck with plain text until I can work out how to do it 🤔

**Comment by Gewerd-Strauss** [comment]
Hmm, maybe restrict it to one of the three (edit/rendered/lp) to begin with?

Preferably lp, but that might also be the most complicated probably. Nonetheless it is a neat feature, albeit the inability to link to the file properly is the biggest setback  (well you can, but it is not given as a suggestion when linking, so you actually must know the entire name).

**Comment by meld-cp** [comment]
Absolutely, locking to live preview would be great, but I'm yet to figure out a way to get Obsidian to stay in that mode.   I might have to ask around.

Re: the linking, do you mind logging a separate issue for that?

**Comment by deusnovus** [comment]
+1 for that feature, please! Also yes, I believe locking it to live preview to avoid corruption issues might be a great idea. Has there been any progress on that?

**Comment by meld-cp** [comment]
Improvements added to this issue in v2.1.1.

There's still a lot missing to get it to the level of a normal note.

It's nice having some MD in the notes now.  Please test!  👍

**Comment by deusnovus** [comment]
I just updated to v2.1.1, but I haven't noticed any changes compared to the version before that... (no MD or styling of any kind)

**Comment by meld-cp** [comment]
I'm not by my desktop right now, but here's an example of how it works from my phone.

It's a similar setup for desktops, you need to switch from source view to reading view to see the formatting (There's a new setting to set your default)

It's not as feature rich as what you'll be used to from a normal note, but I'm happy we can now have formatted encrypted notes.

![MP4_20230409_002002.gif](https://user-images.githubusercontent.com/18450687/230721024-dd87fd5b-dc80-43a9-a82d-1c6928ecbaa0.gif)

**Comment by deusnovus** [comment]
Sorry, the GIF above doesn't animate, could you please send a video screen recording? I'm on macOS / iOS at the moment (currently out of town, can't test on my Fedora machine), but when on Reading View, there are no markdown tools, as well as no way to edit notes / go to Edit mode.

![nomarkdown](https://user-images.githubusercontent.com/32219080/230722336-b1c6e6ee-26a7-4024-84f7-9589977ef85b.jpg)

**Comment by deusnovus** [comment]
Okay, I managed to get things working properly! Fantastic work, it's a great start indeed! Now, I wonder if there's any way for the encrypted notes to be aligned like the default Obsidian notes in the center of the editing space, as opposed to the far left...

**Comment by meld-cp** [comment]
I'll close this for now, there're still some things missing but aside from duplicating every feature from the normal note view, I don't have an easy way to implement them.

So, I'll rely on people creating issues and going from there.
