### ISSUE TITLE
.encrypted-files are not suggested for linking

### ISSUE THREAD

**Issue by Gewerd-Strauss** [meld-cp/obsidian-encrypt#59]
Hmm, maybe restrict it to one of the three (edit/rendered/lp) to begin with?

~~Preferably lp, but that might also be the most complicated probably. Nonetheless it is a neat feature, albeit t~~The inability to link to the file properly is the biggest setback  (well you can, but it is not given as a suggestion when linking, so you actually must know the entire name).

_Originally posted by @Gewerd-Strauss in https://github.com/meld-cp/obsidian-encrypt/issues/48#issuecomment-1318219240_

---

I've tested this in the auto-purging testvault to ensure this was not some strange plugin interaction between one of the 97 plugins installed, and it wasn't. Below can be seen a screenshot showcasing two things:

1. Encrypted files are still linkable (and I tested that the correct file is opened if a markdown file of the same name exists within the same location as the `.encrypted`-note).
2. However, encrypted files are not given as suggestion when creating a blank link in another note. To be precise, you must type out the entire filename (including the file extension `.encrypted`) by hand to link to the encrypted note. 

![grafik](https://user-images.githubusercontent.com/80548781/202636119-3c41d598-da2c-469b-8d81-e5b372c2dd59.png)

Hopefully this can be fixed because otherwhise this reduces viability quite a bit.
Additionally, they (obviously) also do not show up on the graph.

---

I've given this issue a bit of thought, and the assumed-to-be-simplest solution I could come up with is to create a note of the same name alongside every encrypted note and automatically add the correct path to the encrypted note as file contents, generating a proxy of sorts.

---

I hope these details are sufficient. I'll be happy to test things if necessary.

Sincerely,  
~Gw

**Comment by meld-cp** [comment]
Thanks @Gewerd-Strauss.

Hmm, apparently it should work already...
https://github.com/obsidianmd/obsidian-api/issues/39


I'll need to look into it a bit further.

**Comment by meld-cp** [comment]
Just found this setting:
![image](https://user-images.githubusercontent.com/18450687/202822105-483d4ee3-d1f4-4804-92da-6252dbd50ddc.png)

Turn that on and it should work 👍

**Comment by Gewerd-Strauss** [comment]
I feel dumb for not remembering that was there :P

Thank you, this resolves the issue.
