### ISSUE TITLE
Feature request: encrypt whole vault

### ISSUE THREAD

**Issue by yuanqiuye** [meld-cp/obsidian-encrypt#6]
Is it possible to:

Set a single password then
- Auto decrypt all MD files when open Obsidian.
- Auto encrypt all MD files when exit Obsidian.

Thanks for this convenient plugin!

**Comment by meld-cp** [comment]
Hi @yuanqiuye, no there isn't sorry.  I think that would add too much complexity to the plugin and deviate from it's original basic intent .   Maybe something like [cryptomator](https://cryptomator.org/) would work for you?
