### ISSUE TITLE
Search open encrypted file

### ISSUE THREAD

**Issue by WrenMcQueary** [meld-cp/obsidian-encrypt#67]
Could it be possible to add support for searching through a `*.encrypted` file that's been accessed via password and is open in the editor?  Similarly to how Obsidian supports using `Ctrl + F` to search through open `*.md` files?

**Comment by meld-cp** [comment]
related to #48

**Comment by ccchan234** [comment]
> related to #48

hi,

i kept my passwords in the encrypted file,

it feel pain today that i found i cant search for the account name and need to do it manually.

read that #48 but i don't understand the relationship to that issue, i am not programmer.

i just feel it should have the "find/search" function to be usable.

thanks

**Comment by meld-cp** [comment]
I don't think searching within `.encrypted` notes will be possible at this time.  You may have to use the inline encrypted version (comment style) to encrypt snippets of text in your normal markdown notes for now.

**Comment by WrenMcQueary** [comment]
With the release of v2.4.0, searching in notes is now possible!  Thanks!

**Comment by tredondo** [comment]
Just to clarify, as of v2.4.5, searching *across the vault* for a keyword present only in a decrypted note does NOT find it:

<img width="848" height="324" alt="Image" src="https://github.com/user-attachments/assets/0cf9be45-37d1-46a8-9489-3b7f4e864b87" />

Searching only works within the open & decrypted note. This should be mentioned in the README.

@ccchan234 use a [proper password manager](https://github.com/keepassxreboot/keepassxc).
