### ISSUE TITLE
How to encrypt an existing note?

### ISSUE THREAD

**Issue by megatronComing** [meld-cp/obsidian-encrypt#68]
I can't find a way to encrypt an existing note.
Someone knows how? thanks

**Comment by meld-cp** [comment]
That feature doesn't exist yet.  And it'll probably have to wait until #48 is resolved.

In the meantime you can use the comment style encryption or copy paste into a blank encrypted note.

**Comment by meld-cp** [comment]
It would be interesting to have a command to encrypt an existing note, and another to turn an encrypted note back into a normal one.

That way (for those that don't mind the note being temporary decrypted) one could use the full, rich, editing capabilities of Obsidian and then re-encrypt when done.

Something to explore.

**Comment by toonvank** [comment]
There's another addon that encrypts your full anki doc but honestly i haven't had a good experience with it since i think the way it works is very counterproductive. If your addon would have current file encryption it would be a great feature

**Comment by meld-cp** [comment]
added in v2.3.0
