### ISSUE TITLE
Pressing "Enter" to confirm password doesn't encrypt selected text

### ISSUE THREAD

**Issue by meld-cp** [meld-cp/obsidian-encrypt#7]
@barbwire08 I've created a new issue here so we can track this separately

Ref: 
https://github.com/meld-cp/obsidian-encrypt/issues/4#issuecomment-808684245

**Comment by meld-cp** [comment]
I can't look at the code right now, but I wonder if it's not recognising the Enter key on the numpad (vs the Return key near Shift) on a standard desktop keyboard.

I can test this out later.

**Comment by barbwire08** [comment]
Thank you very much meld-cp. I just tried encrypting using the Return key
near the Shift and it worked! Thank you again.

**Comment by meld-cp** [comment]
No problem, thanks for logging the issue, it will be fixed in the next release.  👍

**Comment by meld-cp** [comment]
Fixed in v1.3.2
