### ISSUE TITLE
Hide `ENCRYPTED` label

### ISSUE THREAD

**Issue by kklot** [meld-cp/obsidian-encrypt#71]
Thanks for this wonderful plugin! could you add an option to remove the label to not _draw attention_ to the fact that there are encrypted notes? With a large number of files, and not highlighting the encrypted notes we have an extra layer of protection I think?
Thanks!

**Comment by meld-cp** [comment]
Hi, as far as I know Obsidian doesn't provide a way to hide the file extension, so we are stuck with it sorry
