### ISSUE TITLE
Change file title of encrypted file

### ISSUE THREAD

**Issue by Padishar24** [meld-cp/obsidian-encrypt#78]
As a workaround to encrypt a whole file and keep markdown I inline-encrypt the completed content.

Now it would be great if the file title would change accordingly to the encryption state. For example:
- **SuperSecretContent.md** (not encrypted)
- **SuperSecretContent - enc.md** (encrypted)

Thanks for this great plugin.

**Comment by meld-cp** [comment]
Hi @Padishar24,

It would be problematic renaming files like that.

Markdown is now supported since v2.1.1, give that a try.
