### ISSUE TITLE
Encrypt In-Place Not Available

### ISSUE THREAD

**Issue by todorvlaev** [meld-cp/obsidian-encrypt#82]
Installed the v2.0.4 on macOS Ventura, and the encrypt in-place action is not available. Creating an encrypted note seems to work. I tried assigning shortcuts to the in-place encrypt/decrypt actions, but no luck either. AFAIU the in-place functionality should be working in 2.0.4?

Thanks in advance!

<img width="700" alt="Screenshot 2023-03-22 at 15 00 47" src="https://user-images.githubusercontent.com/2630223/226928153-49b76147-7f74-470c-8794-871b6eecf98c.png">

**Comment by meld-cp** [comment]
Hi @todorvlaev, please confirm you have some text selected before trying to encrypt in place.

**Comment by todorvlaev** [comment]
I'm sure I did but I can't reproduce it anymore 😳 During the weekend, the first time I got it to work was on iPad. I tried with a new vault now on the Mac and everything seems to work also from scratch. Sorry about the noise!

**Comment by meld-cp** [comment]
No problem @todorvlaev 👍
