### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by NoAvailableNameLeft** [meld-cp/obsidian-encrypt#83]
I really wanted to be able to encrypt notes and installed this plugin. Issues are:

1) It doesn't sync between my obsidian instances, how do I make it do that.

2) I cut-and-pasted a long note into it. When I go back it has removed a lot of the note and reformatted. I carefully put the content back in and precisely edited it as I wanted. When I came back it again was missing content and formatting (though different than the last time). Is there a note-length constraint? How do I get it to work properly and not modify things?

**Comment by NoAvailableNameLeft** [comment]
I'm not sure what info you need. So far the problem in #2 hasn't come back, the note has now stayed as edited.

I would still like to know how to see my encrypted notes on all my devices.

**Comment by meld-cp** [comment]
Hi @NoAvailableNameLeft,

I need the steps to reproduce your issues at my end to confirm any bugs I need to fix.

I don't use the built-in sync from obsidian, so I won't be much use there.

As for issue 2, there are no limits imposed on purpose.  Can you provide an example note and the steps to reproduce the issue?

Also, markdown is not supported in encrypted notes at this time, so formatting will be lost if you copy paste (see issue #48)

**Comment by NoAvailableNameLeft** [comment]
Well, I don't have a sample for issue 2 so we'll have to drop that. It worked the 2nd time around.

I hope in the future you can fix it to sync. I guess I'll have to manually make a different note in each Obsidian instance and then work on keeping them all updated manually.
