### ISSUE TITLE
Recursive Encryption [Enhancement]

### ISSUE THREAD

**Issue by rajeget** [meld-cp/obsidian-encrypt#9]
Thanks for this great plugin .

Can we have feature wherein we rightclick a folder and recursively all file and folders are encrypted under it ?

**Comment by meld-cp** [comment]
Hi, sorry, but that's fundamentally different to the current design of the plugin, so it would mean taking it in a new direction (with it's own set of problems).   You might want to look into encrypting the whole vault with 3rd party software instead.
