### ISSUE TITLE
Encrypting text in-place in a table breaks

### ISSUE THREAD

**Issue by achampion** [meld-cp/obsidian-encrypt#93]
If you in-place encrypt a piece of text in a table then in reading mode the table is removed.
However in preview mode the table looks fine.

It would also be good to be able to show decrypted text in preview mode.

**Comment by meld-cp** [comment]
Seems like if the cell contains "🔐α " it breaks the obsidian table reading view renderer.

That's a bug that will have to be logged with Obsidian.

I'm not able to fix that but I can look into changing the encryped prefix a little so that it renders correctly in this scenario.

**Comment by meld-cp** [comment]
Ok, looked it over, it's not a bug with Obsidian...  fix coming soon 👍
