### ISSUE TITLE
File decryption by python

### ISSUE THREAD

**Issue by Sil3ntD3s** [meld-cp/obsidian-encrypt#94]
It is possible to decrypt file using python or external software?
I can't find any way to decrypt '.encrypted' extension file.

Especially i want to use python script to append few lines into the encrypted note.

**Comment by meld-cp** [comment]
Maybe.

You'd have to translate the class below to python and try it. 

https://github.com/meld-cp/obsidian-encrypt/blob/main/src/services/CryptoHelper.ts 


.encrypted files are just JSON.  Decode it and pass the encrypted bytes to the translated decryptbase64 method in your python module.
